export const SAMPLE_MISSIONS = [
  {
    id: 'mission-1',
    title: 'Why Is the Plant Dying?',
    description: 'A mysterious illness is spreading through the school greenhouse. Can you diagnose what\'s wrong before it\'s too late?',
    storyline: 'The school greenhouse caretaker noticed that several plants have been wilting despite regular watering. Brown spots are appearing on leaves, and some plants have stopped growing entirely. Your mission: investigate the evidence, identify the cause, and save the greenhouse!',
    grade: 7,
    category: 'rescue',
    difficulty: 'easy',
    xp_reward: 150,
    estimated_minutes: 25,
    cover_image: '/missions/greenhouse.jpg',
    tags: ['photosynthesis', 'plant biology', 'ecosystems'],
    is_published: true,
    created_by: 'system',
    created_at: new Date().toISOString(),
  },
  {
    id: 'mission-2',
    title: 'Unknown Cell Investigation',
    description: 'A mysterious cell sample has arrived at the lab. Analyze the evidence to determine if it\'s plant, animal, or something else entirely.',
    storyline: 'A research team discovered an unusual organism near the local river. They need your expertise to identify the cell type. Study the microscope slides, compare the organelles, and deliver your expert analysis.',
    grade: 7,
    category: 'investigation',
    difficulty: 'easy',
    xp_reward: 150,
    estimated_minutes: 20,
    cover_image: '/missions/cell.jpg',
    tags: ['cell biology', 'microscopy', 'organelles'],
    is_published: true,
    created_by: 'system',
    created_at: new Date().toISOString(),
  },
  {
    id: 'mission-3',
    title: 'Poisonous Mushroom Mystery',
    description: 'Three students fell ill after a nature hike. Investigate the mushroom samples to identify the culprit.',
    storyline: 'After a school nature hike, three students reported stomach pain and dizziness. The school nurse suspects mushroom poisoning. You\'ve been given samples of every mushroom collected during the hike. Can you identify the toxic species before more students are affected?',
    grade: 7,
    category: 'mystery',
    difficulty: 'medium',
    xp_reward: 200,
    estimated_minutes: 30,
    cover_image: '/missions/mushroom.jpg',
    tags: ['fungi', 'toxicology', 'identification'],
    is_published: true,
    created_by: 'system',
    created_at: new Date().toISOString(),
  },
  {
    id: 'mission-4',
    title: 'Medical Detective',
    description: 'A patient has mysterious symptoms. Analyze their vitals, blood work, and medical history to find the diagnosis.',
    storyline: 'A 14-year-old student arrives at the clinic with fatigue, rapid heartbeat, and pale skin. As the medical detective on duty, you must review all available data and determine what\'s wrong.',
    grade: 8,
    category: 'mystery',
    difficulty: 'medium',
    xp_reward: 250,
    estimated_minutes: 35,
    cover_image: '/missions/medical.jpg',
    tags: ['human body', 'blood', 'diagnosis'],
    is_published: true,
    created_by: 'system',
    created_at: new Date().toISOString(),
  },
  {
    id: 'mission-5',
    title: 'Epidemic at School',
    description: 'A mysterious illness is spreading rapidly through the school. Track the outbreak and stop it.',
    storyline: 'Monday morning: 5 students absent. Tuesday: 23. Wednesday: 67. Something is spreading fast through your school. You\'ve been assigned as the junior epidemiologist. Map the spread, identify the pathogen, and recommend containment strategies.',
    grade: 8,
    category: 'crisis',
    difficulty: 'hard',
    xp_reward: 350,
    estimated_minutes: 45,
    cover_image: '/missions/epidemic.jpg',
    tags: ['epidemiology', 'pathogens', 'public health'],
    is_published: true,
    created_by: 'system',
    created_at: new Date().toISOString(),
  },
  {
    id: 'mission-6',
    title: 'Genetics Laboratory',
    description: 'Solve a family inheritance mystery using Punnett squares and genetic analysis.',
    storyline: 'A family has come to the genetics lab with questions about a hereditary condition appearing in their family tree. Using DNA samples and family records, you must trace the inheritance pattern and predict the risk for future generations.',
    grade: 9,
    category: 'lab',
    difficulty: 'hard',
    xp_reward: 400,
    estimated_minutes: 50,
    cover_image: '/missions/genetics.jpg',
    tags: ['genetics', 'DNA', 'inheritance', 'Punnett squares'],
    is_published: true,
    created_by: 'system',
    created_at: new Date().toISOString(),
  },
  {
    id: 'mission-7',
    title: 'Ecosystem Collapse',
    description: 'A local lake ecosystem is collapsing. Identify the cascade of causes before it\'s too late.',
    storyline: 'Fish are dying in Lake Meridian. Water samples show alarming changes. The local community depends on this lake. As a junior ecologist, you must analyze the food web, study the water chemistry data, and propose a restoration plan.',
    grade: 9,
    category: 'crisis',
    difficulty: 'hard',
    xp_reward: 400,
    estimated_minutes: 50,
    cover_image: '/missions/ecosystem.jpg',
    tags: ['ecology', 'food webs', 'water chemistry', 'conservation'],
    is_published: true,
    created_by: 'system',
    created_at: new Date().toISOString(),
  },
  {
    id: 'mission-8',
    title: 'Build a Biosphere on Mars',
    description: 'Design a self-sustaining ecosystem for a Mars colony using your biology knowledge.',
    storyline: 'The year is 2045. Humanity\'s first Mars colony needs a biosphere to sustain 100 colonists. You\'re on the biology team. Design the perfect closed ecosystem, balancing producers, consumers, and decomposers in a pressurized dome.',
    grade: 9,
    category: 'investigation',
    difficulty: 'hard',
    xp_reward: 500,
    estimated_minutes: 60,
    cover_image: '/missions/mars.jpg',
    tags: ['ecosystems', 'space biology', 'sustainability', 'food chains'],
    is_published: true,
    created_by: 'system',
    created_at: new Date().toISOString(),
  },
]

export const ACHIEVEMENTS_DATA = [
  { id: 'ach-1', name: 'First Mission', description: 'Complete your first mission', icon: '🚀', condition_type: 'missions_completed', condition_value: 1 },
  { id: 'ach-2', name: 'Science Detective', description: 'Complete 3 mystery missions', icon: '🔍', condition_type: 'mystery_missions', condition_value: 3 },
  { id: 'ach-3', name: 'Lab Expert', description: 'Complete 5 lab missions', icon: '🧪', condition_type: 'lab_missions', condition_value: 5 },
  { id: 'ach-4', name: 'Streak Master', description: 'Maintain a 7-day streak', icon: '🔥', condition_type: 'streak_days', condition_value: 7 },
  { id: 'ach-5', name: 'XP Collector', description: 'Earn 1000 XP', icon: '⭐', condition_type: 'total_xp', condition_value: 1000 },
  { id: 'ach-6', name: 'Ecosystem Expert', description: 'Complete all ecosystem missions', icon: '🌍', condition_type: 'ecosystem_missions', condition_value: 3 },
  { id: 'ach-7', name: 'Genetics Master', description: 'Complete the Genetics Laboratory mission with 90%+ score', icon: '🧬', condition_type: 'genetics_score', condition_value: 90 },
  { id: 'ach-8', name: 'Perfect Score', description: 'Score 100% on any mission', icon: '💯', condition_type: 'perfect_score', condition_value: 1 },
]
